import Fluent
import Foundation
import Vapor

/// Represents a registered WebAuthn / Passkey credential associated with a user.
final class UserPasskey: Model, @unchecked Sendable {
    static let schema = "user_passkeys"

    @ID(key: .id)
    var id: UUID?

    @Parent(key: "user_id")
    var user: User

    /// Base64URL-encoded credential ID generated by the authenticator.
    @Field(key: "credential_id")
    var credentialID: String

    /// Raw COSE public key bytes.
    @Field(key: "public_key")
    var publicKey: Data

    /// Signature counter to detect cloned authenticators / replay attacks.
    @Field(key: "current_sign_count")
    var currentSignCount: Int64

    /// User-assigned label (e.g. "MacBook Pro", "iPhone 16", "YubiKey 5C").
    @Field(key: "nickname")
    var nickname: String

    /// Authenticator Attestation GUID if provided during registration.
    @OptionalField(key: "aaguid")
    var aaguid: String?

    /// JSON-encoded array of supported transports (e.g. `["internal", "hybrid", "usb"]`).
    @OptionalField(key: "transports")
    var transports: String?

    @Timestamp(key: "created_at", on: .create)
    var createdAt: Date?

    @OptionalField(key: "last_used_at")
    var lastUsedAt: Date?

    init() {}

    init(
        id: UUID? = nil,
        userID: User.IDValue,
        credentialID: String,
        publicKey: Data,
        currentSignCount: Int64 = 0,
        nickname: String,
        aaguid: String? = nil,
        transports: [String]? = nil
    ) {
        self.id = id
        self.$user.id = userID
        self.credentialID = credentialID
        self.publicKey = publicKey
        self.currentSignCount = currentSignCount
        self.nickname = nickname
        self.aaguid = aaguid
        if let transports, !transports.isEmpty {
            self.transports = (try? String(data: JSONEncoder().encode(transports), encoding: .utf8))
        } else {
            self.transports = nil
        }
    }
}

extension UserPasskey {
    var transportsList: [String] {
        guard let transports, let data = transports.data(using: .utf8) else {
            return []
        }
        return (try? JSONDecoder().decode([String].self, from: data)) ?? []
    }

    struct PublicDTO: Content, Sendable {
        let id: UUID
        let nickname: String
        let aaguid: String?
        let transports: [String]
        let createdAt: Date?
        let lastUsedAt: Date?
    }

    func toPublicDTO() throws -> PublicDTO {
        PublicDTO(
            id: try requireID(),
            nickname: nickname,
            aaguid: aaguid,
            transports: transportsList,
            createdAt: createdAt,
            lastUsedAt: lastUsedAt
        )
    }
}
